### ISSUE TITLE
Seek feature is not working, also Dashboard not working for me.

### ISSUE THREAD

**Issue by anubhavhirani** [pxsx/Discord-Musik-Bot-With-Dashboard#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pxsx** [comment]
Please provide me the steps so i can reproduce it on my end

also download the prebuilded dashboard from the releases and drag it into /dist/client
That should fix your issue with the dashboard
